### ISSUE TITLE
Actron Neo reports battery low in remote sensors

### ISSUE THREAD

**Issue by sschwetz** [MikeJMcGuire/hass-actron#12]
I have installed your add on and have set it up and it works 99% effectively. However it is reporting that the battery is low in the remote sensors when this is not the case. 

I would be more than happy to support you with access to my account to iron out this wrinkle

**Comment by MikeJMcGuire** [comment]
Howdy, can you add a comment on the blog site and then I can contact you privately to talk through account details for testing.

**Comment by MikeJMcGuire** [comment]
Closing as this add-on is for the actron connect. Please raise an issue against the actronque repo if still an issue.
