### ISSUE TITLE
Port 80 Binding while using Nginx Proxy Manager

### ISSUE THREAD

**Issue by 2wenty2wo** [MikeJMcGuire/hass-actron#7]
Hi,

I've really wanted to use this plugin but unfortunately I'm already using port 80 for the default Nginx Proxy Manager Add-on. What is the best solution to run your hass-actron add-on while still being able to use the Proxy Manager?

Sorry if this is a stupid question.

Thank you.

**Comment by MikeJMcGuire** [comment]
Howdy - move the other add-on to a different port. The actron add-on must be on port 80, most other services don't.
