### ISSUE TITLE
Additional Sensors

### ISSUE THREAD

**Issue by sumur1au** [MikeJMcGuire/hass-actron#9]
Hi Mike,

Is it possible to expose the isInESP_Mode & fanIsCont as sensors in Home Assistant. Want to make sure that no one changes the optimum operating conditions. 

Many thanks for all your work with the add on and integration

**Comment by MikeJMcGuire** [comment]
Howdy - done. Cheers mate!

**Comment by sumur1au** [comment]
Thank you so much Mike, you are a legend. The integration has been working great. Love your handwork mate :)
